package com.simon.rag.domain.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.Data;

/**
 * DTOs (Data Transfer Objects) — used for request body deserialization.
 * All validation annotations follow Alibaba Java Coding Standards.
 */
public final class Dtos {

    private Dtos() {}

    // ----------------------------------------------------------------
    //  Auth
    // ----------------------------------------------------------------

    @Data
    public static class LoginRequest {

        @NotBlank(message = "Username must not be blank")
        @Size(min = 3, max = 50, message = "Username must be 3-50 characters")
        private String username;

        @NotBlank(message = "Password must not be blank")
        @Size(min = 6, max = 100, message = "Password must be 6-100 characters")
        private String password;
    }

    // ----------------------------------------------------------------
    //  Chat
    // ----------------------------------------------------------------

    @Data
    public static class ChatRequest {

        @NotBlank(message = "Question must not be blank")
        @Size(max = 2000, message = "Question must not exceed 2000 characters")
        private String question;

        /**
         * Optional — filter retrieval to a specific knowledge category.
         * Values: PROJECT_EXPERIENCE | STUDY_NOTES | CODE_SAMPLE | null (all)
         */
        private String category;

        /** Session ID for conversation grouping — generated by client */
        @NotBlank(message = "Session ID must not be blank")
        private String sessionId;
    }

    // ----------------------------------------------------------------
    //  Document upload
    // ----------------------------------------------------------------

    @Data
    public static class DocumentUploadRequest {

        @NotBlank(message = "Category must not be blank")
        private String category;   // PROJECT_EXPERIENCE | STUDY_NOTES | CODE_SAMPLE

        /** Optional description */
        @Size(max = 500, message = "Description must not exceed 500 characters")
        private String description;
    }
}